apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8
    app.kubernetes.io/part-of: mc-three-scenarios
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-kapq-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-lgm8@sha256:12bde5999f474c60e72bc76a80144289348b8d58c5357323237c2dc0c5444c9b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
